### ISSUE TITLE
关于初次访问可能无法屏蔽的问题及解决办法

### ISSUE THREAD

**Issue by ximalaya22** [wilson7yz/PurifyGithubSearchPage#2]
由于在首次加载页面时，脚本执行的时间点可能早于GitHub页面中目标元素的渲染完成。由于GitHub使用的是动态加载（AJAX）技术，页面的一部分内容可能在脚本执行后才被加载。这就意味着在脚本执行时，需要操作的DOM元素可能还不存在。

为了解决这个问题，需要确保你的脚本在目标元素加载完成后再执行。这可以通过几种方法来实现：

1. **使用MutationObserver：** 这是一个现代的API，用于监听DOM的变化。你可以设置一个观察者来监听整个文档或特定元素的变化，一旦发现变化，就执行你的函数。

2. **设置延时执行：** 尽管这不是一个很好的解决方案，但你可以在你的脚本中加入延时，使其在页面加载一段时间后执行。这并不能保证在所有情况下都有效，因为加载时间会根据用户的网络状况和GitHub服务器的响应时间而有所不同。

3. **周期性检查元素是否存在：** 在你的脚本中加入一个循环，每隔一段时间检查一次目标元素是否存在。一旦发现目标元素，就执行你的函数。这与使用MutationObserver类似，但效率较低。

以下是使用`MutationObserver`的一个示例：

```javascript
(function() {
    'use strict';

    const dinnerNames = ["cirosantilli", "cheezcharmer","pxvr-official","zaohmeing","zhaohmng-outlook-com","Daravai1234","codin-stuffs"];

    function fuckDinner() {
        // 你原来的函数实现
        ...
    }

    const observer = new MutationObserver(mutations => {
        mutations.forEach(mutation => {
            if (mutation.addedNodes.length) {
                fuckDinner();
            }
        });
    });

    // 开始观察整个文档的变化
    observer.observe(document.body, { childList: true, subtree: true });

})();
```

这段代码会创建一个`MutationObserver`，它会监视整个文档的变化。当检测到新的节点被添加到文档时，它会执行`fuckDinner`函数。

请注意，使用`MutationObserver`可能会对性能产生一些影响，尤其是在一个频繁变化的页面上。因此，建议仅观察必要的DOM元素，或者在确定不再需要时断开观察器。

感谢GPT4的帮助

**Comment by lucas7yzz** [comment]
可以，兄弟。

**Comment by lucas7yzz** [comment]
待会改一下
